# Generated by Django 4.2.7 on 2026-04-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='News Title')),
                ('content', models.TextField(verbose_name='News Content')),
                ('date_display', models.CharField(max_length=50, verbose_name='Display Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='IGN (Game Name)')),
                ('game_type', models.CharField(choices=[('BR', 'Battle Royale'), ('CS', 'Counter Strike')], max_length=2, verbose_name='Game Type')),
                ('role', models.CharField(choices=[('Rusher', 'Rusher'), ('Sniper', 'Sniper'), ('Support', 'Support'), ('Assaulter', 'Assaulter')], max_length=20, verbose_name='Playing Role')),
                ('rank', models.CharField(max_length=50, verbose_name='Rank')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('id_code', models.CharField(max_length=12, unique=True, verbose_name='Game UID')),
                ('contact', models.CharField(max_length=15, verbose_name='WhatsApp Number')),
                ('experience', models.CharField(choices=[('Beginner', 'Beginner (0-6 months)'), ('Intermediate', 'Intermediate (6 months-2 years)'), ('Advanced', 'Advanced (2-5 years)'), ('Pro', 'Pro (5+ years)')], max_length=20, verbose_name='Experience Level')),
                ('playing_time', models.CharField(choices=[('Morning', 'Morning (6AM - 12PM)'), ('Afternoon', 'Afternoon (12PM - 6PM)'), ('Evening', 'Evening (6PM - 12AM)'), ('Night', 'Night (12AM - 6AM)'), ('Flexible', 'Flexible (Any time)')], max_length=20, verbose_name='Preferred Playing Time')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Short Bio')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified Player')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tournament Title')),
                ('prize', models.CharField(max_length=50, verbose_name='Win Prize')),
                ('entry_fee', models.CharField(default='Free', max_length=20, verbose_name='Entry Fee')),
                ('per_kill', models.CharField(default='N/A', max_length=20, verbose_name='Per Kill Prize')),
                ('date', models.DateField(verbose_name='Tournament Date')),
                ('time', models.TimeField(verbose_name='Match Time')),
                ('mode', models.CharField(choices=[('Solo', 'Solo'), ('Duo', 'Duo'), ('Squad', 'Squad'), ('CS Squad', 'CS Squad')], max_length=20, verbose_name='Team Mode')),
                ('map_name', models.CharField(default='Bermuda', max_length=50, verbose_name='Map Name')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Full', 'Full'), ('Coming Soon', 'Coming Soon'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Open', max_length=20, verbose_name='Status')),
                ('max_slots', models.PositiveIntegerField(default=50, verbose_name='Maximum Slots')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tournament Description')),
                ('rules', models.TextField(blank=True, null=True, verbose_name='Custom Rules')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, verbose_name='Player Name')),
                ('team_name', models.CharField(max_length=100, verbose_name='Team Name')),
                ('contact_number', models.CharField(max_length=15, verbose_name='WhatsApp Number')),
                ('slot_number', models.PositiveIntegerField(verbose_name='Team Slot Number')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, verbose_name='Payment Status')),
                ('payment_amount', models.CharField(blank=True, max_length=20, null=True, verbose_name='Payment Amount')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='squad.tournament')),
            ],
            options={
                'verbose_name': 'Tournament Registration',
                'verbose_name_plural': 'Tournament Registrations',
                'ordering': ['-registered_at'],
                'unique_together': {('tournament', 'slot_number')},
            },
        ),
    ]
