# Generated by Django 5.1 on 2026-05-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('Today', 'Today'), ('Aavti Kale', 'Aavti Kale'), ('Param Day', 'Param Day'), ('5 Days Pachi', '5 Days Pachi'), ('10 Days Pachi', '10 Days Pachi')], default='Today', max_length=20, verbose_name='Status'),
        ),
    ]
