# Generated by Django 5.1 on 2026-07-16 14:12

from django.db import migrations, models


def normalize_tournament_settings(apps, schema_editor):
    Tournament = apps.get_model('squad', 'Tournament')
    slot_rules = {
        ('BR Rank', 'Solo'): 48,
        ('BR Rank', 'Duo'): 24,
        ('BR Rank', 'Squad'): 12,
        ('Clash Squad', 'Solo'): 2,
        ('Clash Squad', 'Duo'): 2,
        ('Clash Squad', 'Squad'): 2,
    }
    valid_team_modes = {'Solo', 'Duo', 'Squad'}

    for tournament in Tournament.objects.all():
        if tournament.mode == 'CS Squad':
            tournament.game_mode = 'Clash Squad'
            tournament.mode = 'Squad'
        else:
            tournament.game_mode = 'BR Rank'
            if tournament.mode not in valid_team_modes:
                tournament.mode = 'Solo'

        if not tournament.map_name:
            tournament.map_name = 'Bermuda'

        tournament.max_slots = slot_rules[(tournament.game_mode, tournament.mode)]
        tournament.save(update_fields=['game_mode', 'mode', 'map_name', 'max_slots'])


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0002_alter_tournament_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game_mode',
            field=models.CharField(choices=[('BR Rank', 'BR Rank'), ('Clash Squad', 'Clash Squad')], default='BR Rank', max_length=20, verbose_name='Game Mode'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_slots',
            field=models.PositiveIntegerField(default=48, verbose_name='Maximum Slots'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='mode',
            field=models.CharField(choices=[('Solo', 'Solo'), ('Duo', 'Duo'), ('Squad', 'Squad')], default='Solo', max_length=20, verbose_name='Team Mode'),
        ),
        migrations.RunPython(normalize_tournament_settings, migrations.RunPython.noop),
    ]
