# Generated by Django 5.1 on 2026-07-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0004_tournament_alert_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Confirmed At'),
        ),
    ]
