# Generated by Django 5.1 on 2026-07-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0003_tournament_game_mode_alter_tournament_max_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='alert_cancelled',
            field=models.BooleanField(default=False, verbose_name='Alert Cancelled'),
        ),
    ]
