# Generated by Django 5.1 on 2026-07-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0004_tournamentregistration_payment_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='device_registration_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='User Device Registration Time'),
        ),
    ]
