# Generated by Django 6.0.5 on 2026-07-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0005_tournamentregistration_device_registration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID'),
        ),
    ]
